name: FleetEase CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: ./fleetease-backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./fleetease-frontend/web
        run: npm install

      - name: Build Frontend
        working-directory: ./fleetease-frontend/web
        run: npm run build
